version: '3'

services:
 alfresco:
    image: hub.xenit.eu/public/alfresco-repository-community:6.2.0-ga
    restart: unless-stopped
    ports:
    - 8080
    environment:
    - INDEX
    - SOLR_SSL=none

 share:
   image: hub.xenit.eu/public/alfresco-share-community:6.2.0
   ports:
    - 8080

 postgresql:
   image: docker.io/xenit/postgres
   environment:
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=admin
   - POSTGRES_DB=alfresco
   restart: unless-stopped

 solr:
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    hostname: solr
    ports:
      - 8080
    environment:
    - ALFRESCO_SSL=none